# Generated by Django 5.0.3 on 2024-05-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='embeded_url',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
