# Generated by Django 5.0.3 on 2024-05-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_housemodel_embeded_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='embeded_url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
